services:
  - type: web
    name: cq-lite
    env: python
    buildCommand: uv add -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: GOOGLE_API_KEY
        sync: false
      - key: NEBIUS_API_KEY
        sync: false
    healthCheckPath: /api/health
    plan: starter